# Generated by Django 6.0.3 on 2026-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
